
[env]
TERM = "xterm-256color"

[font]
size = 10

[font.normal]
family = "Hack Nerd Font"

[window]
decorations = "none"
dynamic_padding = true
dynamic_title = true
resize_increments = true

[window.dimensions]
columns = 80
lines = 24

[general]
import = ["/home/tim/.config/alacritty/gruvbox_dark.toml"]
