import = ["/home/tim/.config/alacritty/gruvbox_dark.toml"]

[env]
TERM = "xterm-256color"

[font]
size = 11.0

[font.normal]
family = "SauceCodePro Nerd Font Mono"

[window]
decorations = "none"
dynamic_padding = true
dynamic_title = true
resize_increments = true

[window.dimensions]
columns = 80
lines = 24
