return {
	c = { "clang-format" },
	cpp = { "clang-format" },
	go = { "goimports", "gofmt" },
	python = { "ruff_organize_imports", "ruff_format" },
	rust = { { "rustfmt", system = true } },
	javascript = { "prettierd" },
	javascriptreact = { "prettierd" },
	typescript = { "prettierd" },
	typescriptreact = { "prettierd" },
	css = { "prettierd" },
	markdown = { "prettierd" },
	yaml = { "prettierd" },
	lua = { "stylua" },
	json = { "jq" },
	toml = { "taplo" },
	-- ["*"] = { "injected" },
	["_"] = { "trim_whitespace", "trim_newlines" },
}
